var session = new QiSession();

function getTemperature(){
  session.service("ALMemory").done(function(memory){
    memory.getData("Device/SubDeviceList/Battery/Temperature/Sensor/Value").done(function(Battery){
      $("#Battery").text(Battery);
    });
    memory.getData("Device/SubDeviceList/Head/Temperature/Sensor/Value").done(function(Head){
      $("#Head").text(Head);
    });
    memory.getData("Device/SubDeviceList/HeadPitch/Temperature/Sensor/Value").done(function(HeadPitch){
      $("#HeadPitch").text(HeadPitch);
    });
    memory.getData("Device/SubDeviceList/HeadYaw/Temperature/Sensor/Value").done(function(HeadYaw){
      $("#HeadYaw").text(HeadYaw);
    });
    memory.getData("Device/SubDeviceList/LAnklePitch/Temperature/Sensor/Value").done(function(LAnklePitch){
      $("#LAnklePitch").text(LAnklePitch);
    });
    memory.getData("Device/SubDeviceList/LAnkleRoll/Temperature/Sensor/Value").done(function(LAnkleRoll){
      $("#LAnkleRoll").text(LAnkleRoll);
    });
    memory.getData("Device/SubDeviceList/LElbowRoll/Temperature/Sensor/Value").done(function(LElbowRoll){
      $("#LElbowRoll").text(LElbowRoll);
    });
    memory.getData("Device/SubDeviceList/LElbowYaw/Temperature/Sensor/Value").done(function(LElbowYaw){
      $("#LElbowYaw").text(LElbowYaw);
    });
    memory.getData("Device/SubDeviceList/LHand/Temperature/Sensor/Value").done(function(LHand){
      $("#LHand").text(LHand);
    });
    memory.getData("Device/SubDeviceList/LHipPitch/Temperature/Sensor/Value").done(function(LHipPitch){
      $("#LHipPitch").text(LHipPitch);
    });
    memory.getData("Device/SubDeviceList/LHipRoll/Temperature/Sensor/Value").done(function(LHipRoll){
      $("#LHipRoll").text(LHipRoll);
    });
    memory.getData("Device/SubDeviceList/LHipYawPitch/Temperature/Sensor/Value").done(function(LHipYawPitch){
      $("#LHipYawPitch").text(LHipYawPitch);
    });
    memory.getData("Device/SubDeviceList/LKneePitch/Temperature/Sensor/Value").done(function(LKneePitch){
      $("#LKneePitch").text(LKneePitch);
    });
    memory.getData("Device/SubDeviceList/LShoulderPitch/Temperature/Sensor/Value").done(function(LShoulderPitch){
      $("#LShoulderPitch").text(LShoulderPitch);
    });
    memory.getData("Device/SubDeviceList/LShoulderRoll/Temperature/Sensor/Value").done(function(LShoulderRoll){
      $("#LShoulderRoll").text(LShoulderRoll);
    });
    memory.getData("Device/SubDeviceList/LWristYaw/Temperature/Sensor/Value").done(function(LWristYaw){
      $("#LWristYaw").text(LWristYaw);
    });
    memory.getData("Device/SubDeviceList/RAnklePitch/Temperature/Sensor/Value").done(function(RAnklePitch){
      $("#RAnklePitch").text(RAnklePitch);
    });
    memory.getData("Device/SubDeviceList/RAnkleRoll/Temperature/Sensor/Value").done(function(RAnkleRoll){
      $("#RAnkleRoll").text(RAnkleRoll);
    });
    memory.getData("Device/SubDeviceList/RElbowRoll/Temperature/Sensor/Value").done(function(RElbowRoll){
      $("#RElbowRoll").text(RElbowRoll);
    });
    memory.getData("Device/SubDeviceList/RElbowYaw/Temperature/Sensor/Value").done(function(RElbowYaw){
      $("#RElbowYaw").text(RElbowYaw);
    });
    memory.getData("Device/SubDeviceList/RHand/Temperature/Sensor/Value").done(function(RHand){
      $("#RHand").text(RHand);
    });
    memory.getData("Device/SubDeviceList/RHipPitch/Temperature/Sensor/Value").done(function(RHipPitch){
      $("#RHipPitch").text(RHipPitch);
    });
    memory.getData("Device/SubDeviceList/RHipRoll/Temperature/Sensor/Value").done(function(RHipRoll){
      $("#RHipRoll").text(RHipRoll);
    });
    memory.getData("Device/SubDeviceList/RHipYawPitch/Temperature/Sensor/Value").done(function(RHipYawPitch){
      $("#RHipYawPitch").text(RHipYawPitch);
    });
    memory.getData("Device/SubDeviceList/RKneePitch/Temperature/Sensor/Value").done(function(RKneePitch){
      $("#RKneePitch").text(RKneePitch);
    });
    memory.getData("Device/SubDeviceList/RShoulderPitch/Temperature/Sensor/Value").done(function(RShoulderPitch){
      $("#RShoulderPitch").text(RShoulderPitch);
    });
    memory.getData("Device/SubDeviceList/RShoulderRoll/Temperature/Sensor/Value").done(function(RShoulderRoll){
      $("#RShoulderRoll").text(RShoulderRoll);
    });
    memory.getData("Device/SubDeviceList/RWristYaw/Temperature/Sensor/Value").done(function(RWristYaw){
      $("#RWristYaw").text(RWristYaw);
    });
  });
}

setInterval("getTemperature()",3000);
